### ISSUE TITLE
pyehd.py ehd = ehd[0,-5:]

### ISSUE THREAD

**Issue by sktyut** [jiyangzhao/pyehd#1]
ehd = ehd[0,-5:]
I don't understand what this line of code means, it is present in pyehd.py at line 34. You split the image into 16 sub-images, I think your code should output EHD in 16*5 dimensions, not 5.

**Comment by jiyangzhao** [comment]
I think it's to get last five values in the `bins[]` array(17*5). It's the global bin array for the selected image.

**Comment by jiyangzhao** [comment]
I didn't consider those 16 sub-images separately, but only the bin values for entire image

**Comment by sktyut** [comment]
Thanks for your answer.
